<a href="/schools/new">Add new school</a>

<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<?php if (isset($schoolData)): ?>
<form action="/schools/ <?= htmlspecialchars($schoolData['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="DELETE">
    <?= ($schoolData['name']) ?>
    <input type="submit" value="Delete">
</form>
<?php endif; ?>

