<form action="/schools" method="post">
    <div>
        <label>
            Name:
            <input type="text" placeholder="Add name of new school" name="school[name]"
                   value="<?= htmlspecialchars($schoolData['name'] ?? ''); ?>">
        </label>
        <?php if(isset($errors['name'])): ?>
        <div><?= $errors['name'] ?></div>
        <?php endif; ?>
    </div>
    <input type="submit" value="Add">
</form>